### ISSUE TITLE
Is it possible to filter out low counts?

### ISSUE THREAD

**Issue by tokestermw** [ikegami-yukino/madoka-python#8]
Hi, thanks for the package.

I'm running word counts on large corpora (e.g. Wikipedia text) and found this package after Python dictionaries was giving me memory errors. 

I'm new to sketching algorithms so forgive my ignorance but is it possible to filter out low counts after building the sketch object? For example, I'd like to get the top 1 million words sorted by counts in descending order. This is to save some memory.

Tangential question: once the counts are in a sketch object, it can't be converted to a dictionary because there is no key information?

Cheers

**Comment by ikegami-yukino** [comment]
Hi.

Please try `filter` method to  filter out low counts (e.g. `sketch.filter(lambda x: x if x > 1000 else 0)`)
But, unfortunately, This library hasn't key information because hashing.

Thanks.

**Comment by tokestermw** [comment]
got it, thanks
